#!#!/bin/bash

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Use scp to transfer the file to the user home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
    echo "$file_path transferred successfully to $username@$server_ip:~/"
else
    echo "Error transferring $file_path to $username@$server_ip:~/"
fi

