#!/bin/bash

# Check if commit message is provided
if [ -z "$1" ]; then
  echo "Please provide a commit message."
  exit 1
fi

# Set your Git personal access token and construct the repository URL
GIT_TOKEN="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"
GIT_USERNAME="amineaith3"
CURRENT_DIR=$(basename "$PWD")
GIT_REPO="https://$GIT_USERNAME:$GIT_TOKEN@github.com/$GIT_USERNAME/$CURRENT_DIR"

# Add all changes
git add .

# Commit changes with the provided message
git commit -m "$1"

# Push changes to the repository using the personal access token
git push $GIT_REPO

# Exit with success status
exit 0

